# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ikyc_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox


class IKYC_SignUp(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(960, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.label_right_pic = QtWidgets.QLabel(self.centralwidget)
        self.label_right_pic.setGeometry(QtCore.QRect(260, 0, 700, 600))
        self.label_right_pic.setText("")
        self.label_right_pic.setPixmap(QtGui.QPixmap("GUI_Login_Page_Pic/signup_right_background.jpg"))
        self.label_right_pic.setScaledContents(True)
        self.label_right_pic.setObjectName("label_right_pic")

        self.login_frame_label = QtWidgets.QLabel(self.centralwidget)
        self.login_frame_label.setGeometry(QtCore.QRect(70, 120, 561, 351))
        self.login_frame_label.setText("")
        self.login_frame_label.setPixmap(QtGui.QPixmap("GUI_Login_Page_Pic/rounded_rectangle.png"))
        self.login_frame_label.setScaledContents(True)
        self.login_frame_label.setObjectName("login_frame_label")

        self.label_logo = QtWidgets.QLabel(self.centralwidget)
        self.label_logo.setGeometry(QtCore.QRect(10, 10, 241, 101))
        self.label_logo.setText("")
        self.label_logo.setPixmap(QtGui.QPixmap("GUI_Login_Page_Pic/ikyc_logo_transparent.png"))
        self.label_logo.setScaledContents(True)
        self.label_logo.setObjectName("label_logo")

        self.label_background = QtWidgets.QLabel(self.centralwidget)
        self.label_background.setGeometry(QtCore.QRect(-10, -10, 971, 611))
        self.label_background.setText("")
        self.label_background.setPixmap(QtGui.QPixmap("GUI_Login_Page_Pic/solidwhite.png"))
        self.label_background.setScaledContents(True)
        self.label_background.setObjectName("label_background")

        self.label_loginText = QtWidgets.QLabel(self.centralwidget)
        self.label_loginText.setGeometry(QtCore.QRect(140, 180, 391, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_loginText.setFont(font)
        self.label_loginText.setTextFormat(QtCore.Qt.PlainText)
        self.label_loginText.setObjectName("label_loginText")

        self.label_username = QtWidgets.QLabel(self.centralwidget)
        self.label_username.setGeometry(QtCore.QRect(140, 260, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(10)
        self.label_username.setFont(font)
        self.label_username.setObjectName("label_username")

        self.label_password = QtWidgets.QLabel(self.centralwidget)
        self.label_password.setGeometry(QtCore.QRect(140, 320, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(10)
        self.label_password.setFont(font)
        self.label_password.setObjectName("label_password")

        self.commandlink_signUpButton = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.commandlink_signUpButton.setGeometry(QtCore.QRect(190, 365, 320, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.commandlink_signUpButton.setFont(font)
        self.commandlink_signUpButton.setIconSize(QtCore.QSize(30, 30))
        self.commandlink_signUpButton.setObjectName("commandlink_signUpButton")
        

        self.commandlink_backButton = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.commandlink_backButton.setGeometry(QtCore.QRect(20, 530, 70, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.commandlink_backButton.setFont(font)
        self.commandlink_backButton.setIconSize(QtCore.QSize(0, 0))
        self.commandlink_backButton.setObjectName("commandlink_backButton")

        self.lineedit_username = QtWidgets.QLineEdit(self.centralwidget)
        self.lineedit_username.setGeometry(QtCore.QRect(260, 260, 251, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        self.lineedit_username.setFont(font)
        self.lineedit_username.setObjectName("linedit_username")

        self.lineedit_password = QtWidgets.QLineEdit(self.centralwidget)
        self.lineedit_password.setGeometry(QtCore.QRect(260, 320, 251, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        self.lineedit_password.setFont(font)
        self.lineedit_password.setObjectName("lineedit_password")
        self.lineedit_password.setEchoMode(QtWidgets.QLineEdit.Password) #Mask the password.

        self.label_background.raise_()
        self.label_right_pic.raise_()
        self.login_frame_label.raise_()
        self.label_logo.raise_()
        self.label_loginText.raise_()
        self.label_username.raise_()
        self.label_password.raise_()
        self.commandlink_signUpButton.raise_()
        self.commandlink_backButton.raise_()
        self.lineedit_username.raise_()
        self.lineedit_password.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "iKYC Login"))
        self.label_loginText.setText(_translate("MainWindow", "Sign up for iKYC!"))
        self.label_username.setText(_translate("MainWindow", "CustomerID"))
        self.label_password.setText(_translate("MainWindow", "Password"))
        self.commandlink_signUpButton.setText(_translate("MainWindow", "Sign up and start face registering"))
        self.commandlink_backButton.setText(_translate("MainWindow", "Back"))
    


    def loginButtonClicked(self):
        username = self.linedit_username.text()
        password = self.lineedit_password.text()
        print("Captured username: " + username)
        print("Captured password: " + password)
        self.checkUsernamePasswordCorrectness(username, password)
    

    def loginWithFaceIDClicked(self):
        print("iKYC login GUI: Attempting to login through FaceID...\n")
        #Function call for calling OpenCV should be written here


    def checkUsernamePasswordCorrectness(self, username:str, password:str) -> bool:
        #Dummy test here.
        if(username == "errtest" and password == "1"):
            self.showErrorPopUpWindow()


    def showErrorPopUpWindow(self):
        popUp = QMessageBox()
        popUp.setWindowTitle("Authentication failed!")
        popUp.setText("Your username or password is incorrect, try again!")
        popUp.show()
        popUp.setIcon(QMessageBox.Critical)
        popUp.setStandardButtons(QMessageBox.Ok)
        popUp.exec_()


    def authenticationSuccess():
        print("Authentication success, directing to main window")
        #Functions about directing to main window




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = IKYC_SignUp()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
