# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'p_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Main(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(960, 600)
        MainWindow.setMinimumSize(QtCore.QSize(960, 600))
        MainWindow.setStyleSheet("background-color: rgb(238, 238, 238);\n"
"font: bold italic 11pt \"Calibri\";")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.side_menu = QtWidgets.QFrame(self.centralwidget)
        self.side_menu.setMaximumSize(QtCore.QSize(200, 16777215))
        self.side_menu.setStyleSheet("\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(198, 213, 234, 255), stop:1 rgba(238, 242, 250, 255));\n"
"font: bold italic 13pt \"Calibri\";")
        self.side_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.side_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.side_menu.setObjectName("side_menu")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.side_menu)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 10)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame = QtWidgets.QFrame(self.side_menu)
        self.frame.setMinimumSize(QtCore.QSize(200, 0))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 90))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 10, 171, 31))
        self.label.setObjectName("label")
        self.label_surname = QtWidgets.QLabel(self.frame)
        self.label_surname.setGeometry(QtCore.QRect(50, 50, 151, 21))
        self.label_surname.setObjectName("label_surname")
        self.verticalLayout_4.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.side_menu)
        self.frame_2.setStyleSheet("")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_14 = QtWidgets.QFrame(self.frame_2)
        self.frame_14.setMinimumSize(QtCore.QSize(0, 60))
        self.frame_14.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton_profile = QtWidgets.QPushButton(self.frame_14)
        self.pushButton_profile.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_profile.setStyleSheet("QPushButton{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(198, 213, 234, 255), stop:1 rgba(238, 242, 250, 255));\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(238, 242, 250);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton#btn1{\n"
"    background-color: rgb(238, 242, 250);\n"
"    border: 0px solid;\n"
"}\n"
"\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/profile.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_profile.setIcon(icon)
        self.pushButton_profile.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_profile.setObjectName("pushButton_profile")
        self.verticalLayout_5.addWidget(self.pushButton_profile)
        self.verticalLayout.addWidget(self.frame_14)
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 60))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_home = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_home.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_home.setStyleSheet("QPushButton{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(198, 213, 234, 255), stop:1 rgba(238, 242, 250, 255));\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(238, 242, 250);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton#btn1{\n"
"    background-color: rgb(238, 242, 250);\n"
"    border: 0px solid;\n"
"}\n"
"\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_home.setIcon(icon1)
        self.pushButton_home.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_home.setObjectName("pushButton_home")
        self.verticalLayout_2.addWidget(self.pushButton_home)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_29 = QtWidgets.QFrame(self.frame_2)
        self.frame_29.setMinimumSize(QtCore.QSize(0, 60))
        self.frame_29.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_29)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.pushButton_wallet = QtWidgets.QPushButton(self.frame_29)
        self.pushButton_wallet.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_wallet.setStyleSheet("QPushButton{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(198, 213, 234, 255), stop:1 rgba(238, 242, 250, 255));\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(238, 242, 250);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton#btn1{\n"
"    background-color: rgb(238, 242, 250);\n"
"    border: 0px solid;\n"
"}\n"
"\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/wallet.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_wallet.setIcon(icon2)
        self.pushButton_wallet.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_wallet.setObjectName("pushButton_wallet")
        self.verticalLayout_8.addWidget(self.pushButton_wallet)
        self.verticalLayout.addWidget(self.frame_29)
        self.frame_30 = QtWidgets.QFrame(self.frame_2)
        self.frame_30.setMinimumSize(QtCore.QSize(0, 60))
        self.frame_30.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_30.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_30.setObjectName("frame_30")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.frame_30)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setSpacing(0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.pushButton_transfer = QtWidgets.QPushButton(self.frame_30)
        self.pushButton_transfer.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_transfer.setStyleSheet("QPushButton{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(198, 213, 234, 255), stop:1 rgba(238, 242, 250, 255));\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(238, 242, 250);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton#btn1{\n"
"    background-color: rgb(238, 242, 250);\n"
"    border: 0px solid;\n"
"}\n"
"\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_transfer.setIcon(icon3)
        self.pushButton_transfer.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_transfer.setObjectName("pushButton_transfer")
        self.verticalLayout_20.addWidget(self.pushButton_transfer)
        self.verticalLayout.addWidget(self.frame_30)
        self.verticalLayout_4.addWidget(self.frame_2)
        self.frame_6 = QtWidgets.QFrame(self.side_menu)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_4.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.side_menu)
        self.frame_7.setMinimumSize(QtCore.QSize(0, 60))
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_logout = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_logout.setMinimumSize(QtCore.QSize(0, 60))
        self.pushButton_logout.setStyleSheet("QPushButton{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(198, 213, 234, 255), stop:1 rgba(238, 242, 250, 255));\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(238, 242, 250);\n"
"    border: 0px solid;\n"
"}\n"
"\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/logout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_logout.setIcon(icon4)
        self.pushButton_logout.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_logout.setObjectName("pushButton_logout")
        self.verticalLayout_3.addWidget(self.pushButton_logout)
        self.verticalLayout_4.addWidget(self.frame_7)
        self.horizontalLayout.addWidget(self.side_menu)
        self.main_page = QtWidgets.QFrame(self.centralwidget)
        self.main_page.setMaximumSize(QtCore.QSize(760, 16777215))
        self.main_page.setStyleSheet("background-color: rgb(247, 247, 247);\n"
"background-color: rgb(238, 242, 250);")
        self.main_page.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_page.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_page.setObjectName("main_page")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.main_page)
        self.horizontalLayout_2.setContentsMargins(0, 5, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.main_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setMinimumSize(QtCore.QSize(800, 0))
        self.stackedWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_profile = QtWidgets.QWidget()
        self.page_profile.setStyleSheet("")
        self.page_profile.setObjectName("page_profile")
        self.frame_27 = QtWidgets.QFrame(self.page_profile)
        self.frame_27.setGeometry(QtCore.QRect(0, 10, 651, 501))
        self.frame_27.setStyleSheet("")
        self.frame_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_27)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox = QtWidgets.QGroupBox(self.frame_27)
        self.groupBox.setStyleSheet("\n"
"\n"
"\n"
"QLineEdit{\n"
"border:0px solid gray;\n"
"border-radius:3px;\n"
"\n"
"}\n"
"QLineEdit#edit1{\n"
"border:2px solid gray;\n"
"border-radius:3px;\n"
"\n"
"}")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.frame_24 = QtWidgets.QFrame(self.groupBox)
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_24)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_18 = QtWidgets.QFrame(self.frame_24)
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_18)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_8 = QtWidgets.QLabel(self.frame_18)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_9.addWidget(self.label_8)
        self.lineEdit_firstname = QtWidgets.QLineEdit(self.frame_18)
        self.lineEdit_firstname.setObjectName("lineEdit_firstname")
        self.verticalLayout_9.addWidget(self.lineEdit_firstname)
        self.horizontalLayout_6.addWidget(self.frame_18)
        self.frame_23 = QtWidgets.QFrame(self.frame_24)
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_23)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_14 = QtWidgets.QLabel(self.frame_23)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_15.addWidget(self.label_14)
        self.lineEdit_lastname = QtWidgets.QLineEdit(self.frame_23)
        self.lineEdit_lastname.setObjectName("lineEdit_lastname")
        self.verticalLayout_15.addWidget(self.lineEdit_lastname)
        self.horizontalLayout_6.addWidget(self.frame_23)
        self.verticalLayout_18.addWidget(self.frame_24)
        self.frame_15 = QtWidgets.QFrame(self.groupBox)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_17 = QtWidgets.QFrame(self.frame_15)
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_17)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_9 = QtWidgets.QLabel(self.frame_17)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_10.addWidget(self.label_9)
        self.lineEdit_gender = QtWidgets.QLineEdit(self.frame_17)
        self.lineEdit_gender.setObjectName("lineEdit_gender")
        self.verticalLayout_10.addWidget(self.lineEdit_gender)
        self.horizontalLayout_7.addWidget(self.frame_17)
        self.frame_16 = QtWidgets.QFrame(self.frame_15)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_10 = QtWidgets.QLabel(self.frame_16)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_11.addWidget(self.label_10)
        self.lineEdit_birthday = QtWidgets.QLineEdit(self.frame_16)
        self.lineEdit_birthday.setObjectName("lineEdit_birthday")
        self.verticalLayout_11.addWidget(self.lineEdit_birthday)
        self.horizontalLayout_7.addWidget(self.frame_16)
        self.frame_26 = QtWidgets.QFrame(self.frame_15)
        self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_26)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_16 = QtWidgets.QLabel(self.frame_26)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_17.addWidget(self.label_16)
        self.lineEdit_phone = QtWidgets.QLineEdit(self.frame_26)
        self.lineEdit_phone.setObjectName("lineEdit_phone")
        self.verticalLayout_17.addWidget(self.lineEdit_phone)
        self.horizontalLayout_7.addWidget(self.frame_26)
        self.verticalLayout_18.addWidget(self.frame_15)
        self.frame_25 = QtWidgets.QFrame(self.groupBox)
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_25)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_15 = QtWidgets.QLabel(self.frame_25)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_16.addWidget(self.label_15)
        self.lineEdit_email = QtWidgets.QLineEdit(self.frame_25)
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.verticalLayout_16.addWidget(self.lineEdit_email)
        self.verticalLayout_18.addWidget(self.frame_25)
        self.verticalLayout_6.addWidget(self.groupBox)
        self.frame_28 = QtWidgets.QFrame(self.frame_27)
        self.frame_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_28)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_changepwd = QtWidgets.QPushButton(self.frame_28)
        self.pushButton_changepwd.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_changepwd.setStyleSheet("border:0px solid;\n"
"border-radius:5px;\n"
"background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(198, 213, 234, 255), stop:1 rgba(238, 242, 250, 255))\n"
"")
        self.pushButton_changepwd.setObjectName("pushButton_changepwd")
        self.horizontalLayout_4.addWidget(self.pushButton_changepwd)
        self.pushButton_edit_profile = QtWidgets.QPushButton(self.frame_28)
        self.pushButton_edit_profile.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_edit_profile.setStyleSheet("QPushButton{border:0px solid;\n"
"border-radius:5px;\n"
"background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(198, 213, 234, 255), stop:1 rgba(238, 242, 250, 255))\n"
"}\n"
"QPushButton#edit2{border:0px solid;\n"
"border-radius:5px;\n"
"background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(98, 197, 146, 255), stop:1 rgba(238, 242, 250, 255))\n"
"}\n"
"\n"
"")
        self.pushButton_edit_profile.setObjectName("pushButton_edit_profile")
        self.horizontalLayout_4.addWidget(self.pushButton_edit_profile)
        self.verticalLayout_6.addWidget(self.frame_28)
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame_27)
        self.groupBox_3.setStyleSheet("\n"
"\n"
"QLineEdit{\n"
"border:0px solid gray;\n"
"border-radius:3px;\n"
"\n"
"}\n"
"")
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.frame_19 = QtWidgets.QFrame(self.groupBox_3)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_19)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame_20 = QtWidgets.QFrame(self.frame_19)
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_20)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_11 = QtWidgets.QLabel(self.frame_20)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_12.addWidget(self.label_11)
        self.lineEdit_id = QtWidgets.QLineEdit(self.frame_20)
        self.lineEdit_id.setObjectName("lineEdit_id")
        self.verticalLayout_12.addWidget(self.lineEdit_id)
        self.horizontalLayout_8.addWidget(self.frame_20)
        self.frame_21 = QtWidgets.QFrame(self.frame_19)
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_21)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_12 = QtWidgets.QLabel(self.frame_21)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_13.addWidget(self.label_12)
        self.lineEdit_certi = QtWidgets.QLineEdit(self.frame_21)
        self.lineEdit_certi.setObjectName("lineEdit_certi")
        self.verticalLayout_13.addWidget(self.lineEdit_certi)
        self.horizontalLayout_8.addWidget(self.frame_21)
        self.frame_22 = QtWidgets.QFrame(self.frame_19)
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_22)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_13 = QtWidgets.QLabel(self.frame_22)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_14.addWidget(self.label_13)
        self.lineEdit_cid = QtWidgets.QLineEdit(self.frame_22)
        self.lineEdit_cid.setObjectName("lineEdit_cid")
        self.verticalLayout_14.addWidget(self.lineEdit_cid)
        self.horizontalLayout_8.addWidget(self.frame_22)
        self.horizontalLayout_9.addWidget(self.frame_19)
        self.verticalLayout_6.addWidget(self.groupBox_3)
        self.frame_pwd = QtWidgets.QFrame(self.page_profile)
        self.frame_pwd.setGeometry(QtCore.QRect(200, 160, 321, 281))
        self.frame_pwd.setStyleSheet("\n"
"QFrame#frame_pwd{border:1px solid gray;\n"
"border-radius:20px;\n"
"background-color:rgb(255, 218, 144);\n"
"\n"
"border-radius:10px;\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.frame_pwd.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pwd.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pwd.setObjectName("frame_pwd")
        self.label_19 = QtWidgets.QLabel(self.frame_pwd)
        self.label_19.setGeometry(QtCore.QRect(100, 20, 151, 16))
        self.label_19.setStyleSheet("background-color:rgb(255, 218, 144);")
        self.label_19.setObjectName("label_19")
        self.lineEdit_p1 = QtWidgets.QLineEdit(self.frame_pwd)
        self.lineEdit_p1.setGeometry(QtCore.QRect(180, 70, 113, 21))
        self.lineEdit_p1.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_p1.setObjectName("lineEdit_p1")
        self.lineEdit_p2 = QtWidgets.QLineEdit(self.frame_pwd)
        self.lineEdit_p2.setGeometry(QtCore.QRect(180, 110, 113, 21))
        self.lineEdit_p2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_p2.setObjectName("lineEdit_p2")
        self.lineEdit_p3 = QtWidgets.QLineEdit(self.frame_pwd)
        self.lineEdit_p3.setGeometry(QtCore.QRect(180, 150, 113, 21))
        self.lineEdit_p3.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_p3.setObjectName("lineEdit_p3")
        self.label_20 = QtWidgets.QLabel(self.frame_pwd)
        self.label_20.setGeometry(QtCore.QRect(50, 70, 111, 16))
        self.label_20.setStyleSheet("background-color:rgb(255, 218, 144);")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.frame_pwd)
        self.label_21.setGeometry(QtCore.QRect(40, 110, 121, 16))
        self.label_21.setStyleSheet("background-color:rgb(255, 218, 144);")
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.frame_pwd)
        self.label_22.setGeometry(QtCore.QRect(20, 150, 151, 16))
        self.label_22.setStyleSheet("background-color:rgb(255, 218, 144);")
        self.label_22.setObjectName("label_22")
        self.pushButton_confirmpwd = QtWidgets.QPushButton(self.frame_pwd)
        self.pushButton_confirmpwd.setGeometry(QtCore.QRect(40, 220, 93, 28))
        self.pushButton_confirmpwd.setStyleSheet("background-color: rgb(98, 197, 146);")
        self.pushButton_confirmpwd.setObjectName("pushButton_confirmpwd")
        self.pushButton_cancelpwd = QtWidgets.QPushButton(self.frame_pwd)
        self.pushButton_cancelpwd.setGeometry(QtCore.QRect(200, 220, 93, 28))
        self.pushButton_cancelpwd.setStyleSheet("background-color: rgb(197, 75, 53);")
        self.pushButton_cancelpwd.setObjectName("pushButton_cancelpwd")
        self.stackedWidget.addWidget(self.page_profile)
        self.page_home = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_home.sizePolicy().hasHeightForWidth())
        self.page_home.setSizePolicy(sizePolicy)
        self.page_home.setObjectName("page_home")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.page_home)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 11)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_8 = QtWidgets.QFrame(self.page_home)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.frame_12 = QtWidgets.QFrame(self.frame_8)
        self.frame_12.setGeometry(QtCore.QRect(440, 110, 301, 451))
        self.frame_12.setStyleSheet("\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(186, 208, 235, 255), stop:1 rgba(238, 242, 250, 255));\n"
"\n"
"border-radius:10px;")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.label_7 = QtWidgets.QLabel(self.frame_12)
        self.label_7.setGeometry(QtCore.QRect(30, 10, 251, 22))
        self.label_7.setStyleSheet("background:transparent")
        self.label_7.setObjectName("label_7")
        self.tableWidget_login = QtWidgets.QTableWidget(self.frame_12)
        self.tableWidget_login.setGeometry(QtCore.QRect(10, 40, 281, 391))
        self.tableWidget_login.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tableWidget_login.setStyleSheet("\n"
"\n"
"QHeaderView                   \n"
"{\n"
"    background:transparent;\n"
"    \n"
"\n"
"}\n"
"QHeaderView::section          \n"
"{                 \n"
"    background-color:rgb(204, 217, 247); \n"
"    border:none;                \n"
"    text-align:center;             \n"
"    min-height:35px;               \n"
"    max-height:35px;               \n"
"    margin-left:0px;              \n"
"    padding-left:0px;\n"
"    border: 0px solid;      \n"
"}\n"
"QTableWidget{\n"
"\n"
"background:rgb(204, 217, 247); \n"
"border:1px solid #242424;\n"
"gridline-color:#242424;\n"
"selection-color:#242424;\n"
"selection-background-color:rgb(204, 217, 247);\n"
"}\n"
"QTableCornerButton::section {\n"
"background-color:rgb(204, 217, 247);\n"
"}")
        self.tableWidget_login.setLineWidth(0)
        self.tableWidget_login.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_login.setCornerButtonEnabled(False)
        self.tableWidget_login.setRowCount(0)
        self.tableWidget_login.setObjectName("tableWidget_login")
        self.tableWidget_login.setColumnCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_login.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_login.setHorizontalHeaderItem(1, item)
        self.frame_11 = QtWidgets.QFrame(self.frame_8)
        self.frame_11.setGeometry(QtCore.QRect(20, 350, 401, 211))
        self.frame_11.setStyleSheet("QFrame#frame_11{border-radius:10px;\n"
"\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(186, 208, 235, 255), stop:1 rgba(238, 242, 250, 255));\n"
"}")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.label_6 = QtWidgets.QLabel(self.frame_11)
        self.label_6.setGeometry(QtCore.QRect(11, 11, 371, 22))
        self.label_6.setStyleSheet("background:transparent")
        self.label_6.setObjectName("label_6")
        self.tableWidget_recentContect = QtWidgets.QTableWidget(self.frame_11)
        self.tableWidget_recentContect.setGeometry(QtCore.QRect(11, 50, 381, 141))
        self.tableWidget_recentContect.setMaximumSize(QtCore.QSize(16777215, 200))
        self.tableWidget_recentContect.setStyleSheet("\n"
"\n"
"QHeaderView                   \n"
"{\n"
"    background:transparent;\n"
"    \n"
"\n"
"}\n"
"QHeaderView::section          \n"
"{                 \n"
"    background-color:rgb(204, 217, 247);;         \n"
"    border:none;                \n"
"    text-align:center;             \n"
"    min-height:35px;               \n"
"    max-height:35px;               \n"
"    margin-left:0px;              \n"
"    padding-left:0px;\n"
"    border: 0px solid;      \n"
"}\n"
"QTableWidget{\n"
"\n"
"background:rgb(204, 217, 247);\n"
"border:1px solid #242424;\n"
"gridline-color:#242424;\n"
"selection-color:#242424;\n"
"selection-background-color:rgb(204, 217, 247);\n"
"\n"
"}\n"
"QTableCornerButton::section {\n"
"background-color:rgb(204, 217, 247);\n"
"}")
        self.tableWidget_recentContect.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_recentContect.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_recentContect.setCornerButtonEnabled(False)
        self.tableWidget_recentContect.setObjectName("tableWidget_recentContect")
        self.tableWidget_recentContect.setColumnCount(3)
        self.tableWidget_recentContect.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_recentContect.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_recentContect.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_recentContect.setHorizontalHeaderItem(2, item)
        self.pushButton_qt = QtWidgets.QPushButton(self.frame_11)
        self.pushButton_qt.setGeometry(QtCore.QRect(260, 10, 131, 28))
        self.pushButton_qt.setStyleSheet("background-color: rgb(98, 197, 146);")
        self.pushButton_qt.setObjectName("pushButton_qt")
        self.frame_13 = QtWidgets.QFrame(self.frame_8)
        self.frame_13.setGeometry(QtCore.QRect(20, 20, 401, 311))
        self.frame_13.setStyleSheet("border-radius:10px;\n"
"\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(186, 208, 235, 255), stop:1 rgba(238, 242, 250, 255));\n"
"")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.label_28 = QtWidgets.QLabel(self.frame_13)
        self.label_28.setGeometry(QtCore.QRect(11, 11, 381, 22))
        self.label_28.setStyleSheet("")
        self.label_28.setObjectName("label_28")
        self.frame_9 = QtWidgets.QFrame(self.frame_13)
        self.frame_9.setGeometry(QtCore.QRect(10, 40, 381, 261))
        self.frame_9.setStyleSheet("background:transparent;")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.label_image = QtWidgets.QLabel(self.frame_9)
        self.label_image.setGeometry(QtCore.QRect(0, 0, 381, 261))
        self.label_image.setObjectName("label_image")
        self.label_29 = QtWidgets.QLabel(self.frame_8)
        self.label_29.setGeometry(QtCore.QRect(450, 80, 101, 21))
        self.label_29.setObjectName("label_29")
        self.label_logintime = QtWidgets.QLabel(self.frame_8)
        self.label_logintime.setGeometry(QtCore.QRect(600, 80, 121, 21))
        self.label_logintime.setObjectName("label_logintime")
        self.label_30 = QtWidgets.QLabel(self.frame_8)
        self.label_30.setGeometry(QtCore.QRect(450, 50, 101, 21))
        self.label_30.setObjectName("label_30")
        self.label_loginid = QtWidgets.QLabel(self.frame_8)
        self.label_loginid.setGeometry(QtCore.QRect(600, 50, 131, 21))
        self.label_loginid.setObjectName("label_loginid")
        self.label_31 = QtWidgets.QLabel(self.frame_8)
        self.label_31.setGeometry(QtCore.QRect(450, 20, 101, 20))
        self.label_31.setObjectName("label_31")
        self.label_loginname = QtWidgets.QLabel(self.frame_8)
        self.label_loginname.setGeometry(QtCore.QRect(600, 20, 151, 20))
        self.label_loginname.setObjectName("label_loginname")
        self.frame_maketransaction_2 = QtWidgets.QFrame(self.frame_8)
        self.frame_maketransaction_2.setGeometry(QtCore.QRect(70, 150, 631, 251))
        self.frame_maketransaction_2.setStyleSheet("QFrame#frame_maketransaction_2{border:1px solid gray;\n"
"border-radius:20px;\n"
"background-color:rgb(255, 218, 144)\n"
"}")
        self.frame_maketransaction_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_maketransaction_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_maketransaction_2.setObjectName("frame_maketransaction_2")
        self.pushButton_cancel_4 = QtWidgets.QPushButton(self.frame_maketransaction_2)
        self.pushButton_cancel_4.setGeometry(QtCore.QRect(500, 210, 93, 28))
        self.pushButton_cancel_4.setStyleSheet("background-color: rgb(197, 75, 53);")
        self.pushButton_cancel_4.setObjectName("pushButton_cancel_4")
        self.lineEdit_From_account_4 = QtWidgets.QLineEdit(self.frame_maketransaction_2)
        self.lineEdit_From_account_4.setGeometry(QtCore.QRect(30, 80, 141, 31))
        self.lineEdit_From_account_4.setStyleSheet("font:rgb(140, 148, 148)")
        self.lineEdit_From_account_4.setText("")
        self.lineEdit_From_account_4.setObjectName("lineEdit_From_account_4")
        self.label_41 = QtWidgets.QLabel(self.frame_maketransaction_2)
        self.label_41.setGeometry(QtCore.QRect(30, 50, 131, 16))
        self.label_41.setStyleSheet("background-color:rgb(255, 218, 144)")
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.frame_maketransaction_2)
        self.label_42.setGeometry(QtCore.QRect(30, 120, 171, 21))
        self.label_42.setStyleSheet("background-color:rgb(255, 218, 144)")
        self.label_42.setObjectName("label_42")
        self.frame_32 = QtWidgets.QFrame(self.frame_maketransaction_2)
        self.frame_32.setGeometry(QtCore.QRect(30, 150, 571, 52))
        self.frame_32.setStyleSheet("QFrame#frame_32{background-color:rgb(255, 218, 144)}")
        self.frame_32.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_32.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_32.setObjectName("frame_32")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_32)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(20)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.lineEdit_To_account_4 = QtWidgets.QLineEdit(self.frame_32)
        self.lineEdit_To_account_4.setText("")
        self.lineEdit_To_account_4.setObjectName("lineEdit_To_account_4")
        self.horizontalLayout_12.addWidget(self.lineEdit_To_account_4)
        self.lineEdit_To_customer_4 = QtWidgets.QLineEdit(self.frame_32)
        self.lineEdit_To_customer_4.setText("")
        self.lineEdit_To_customer_4.setObjectName("lineEdit_To_customer_4")
        self.horizontalLayout_12.addWidget(self.lineEdit_To_customer_4)
        self.lineEdit_amount_4 = QtWidgets.QLineEdit(self.frame_32)
        self.lineEdit_amount_4.setText("")
        self.lineEdit_amount_4.setObjectName("lineEdit_amount_4")
        self.horizontalLayout_12.addWidget(self.lineEdit_amount_4)
        self.comboBox_ttype_4 = QtWidgets.QComboBox(self.frame_32)
        self.comboBox_ttype_4.setObjectName("comboBox_ttype_4")
        self.comboBox_ttype_4.addItem("")
        self.comboBox_ttype_4.addItem("")
        self.horizontalLayout_12.addWidget(self.comboBox_ttype_4)
        self.pushButton_make2_4 = QtWidgets.QPushButton(self.frame_maketransaction_2)
        self.pushButton_make2_4.setGeometry(QtCore.QRect(390, 210, 93, 28))
        self.pushButton_make2_4.setStyleSheet("background-color: rgb(98, 197, 146);")
        self.pushButton_make2_4.setObjectName("pushButton_make2_4")
        self.label_43 = QtWidgets.QLabel(self.frame_maketransaction_2)
        self.label_43.setGeometry(QtCore.QRect(260, 10, 161, 16))
        self.label_43.setStyleSheet("background-color:rgb(255, 218, 144)")
        self.label_43.setObjectName("label_43")
        self.horizontalLayout_3.addWidget(self.frame_8)
        self.stackedWidget.addWidget(self.page_home)
        self.page_wallet = QtWidgets.QWidget()
        self.page_wallet.setObjectName("page_wallet")
        self.tableWidget_accounts = QtWidgets.QTableWidget(self.page_wallet)
        self.tableWidget_accounts.setGeometry(QtCore.QRect(30, 40, 631, 201))
        self.tableWidget_accounts.setMinimumSize(QtCore.QSize(631, 0))
        self.tableWidget_accounts.setStyleSheet("QHeaderView                   \n"
"{\n"
"    background:transparent;\n"
"    \n"
"\n"
"}\n"
"QHeaderView::section          \n"
"{                 \n"
"    background-color:rgb(238, 242, 250);          \n"
"    border:none;                \n"
"    text-align:center;             \n"
"    min-height:35px;               \n"
"    max-height:35px;               \n"
"    margin-left:0px;              \n"
"    padding-left:0px;\n"
"    border: 0px solid;      \n"
"}\n"
"QTableWidget{\n"
"\n"
"background:rgb(238, 242, 250); \n"
"border:1px solid #242424;\n"
"gridline-color:#242424;\n"
"selection-color:#242424;\n"
"selection-background-color:rgb(198, 213, 234);\n"
"\n"
"}\n"
"QTableCornerButton::section {\n"
"background-color:rgb(238, 242, 250);  \n"
"}")
        self.tableWidget_accounts.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_accounts.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_accounts.setObjectName("tableWidget_accounts")
        self.tableWidget_accounts.setColumnCount(5)
        self.tableWidget_accounts.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_accounts.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_accounts.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_accounts.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_accounts.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_accounts.setHorizontalHeaderItem(4, item)
        self.label_2 = QtWidgets.QLabel(self.page_wallet)
        self.label_2.setGeometry(QtCore.QRect(30, 260, 191, 16))
        self.label_2.setObjectName("label_2")
        self.tableWidget_transactions = QtWidgets.QTableWidget(self.page_wallet)
        self.tableWidget_transactions.setGeometry(QtCore.QRect(30, 301, 631, 251))
        self.tableWidget_transactions.setStyleSheet("QHeaderView                   \n"
"{\n"
"    background:transparent;\n"
"}\n"
"QHeaderView::section          \n"
"{                 \n"
"    background-color:rgb(238, 242, 250);          \n"
"    border:none;                \n"
"    text-align:center;             \n"
"    min-height:35px;               \n"
"    max-height:35px;               \n"
"    margin-left:0px;              \n"
"    padding-left:0px;\n"
"    border: 0px solid        \n"
"}\n"
"QTableWidget{\n"
"\n"
"background:rgb(238, 242, 250);\n"
"border:1px solid #242424;\n"
"gridline-color:#242424;\n"
"selection-color:#242424;\n"
"selection-background-color:rgb(198, 213, 234);\n"
"\n"
"}\n"
"QTableCornerButton::section {\n"
"background-color:rgb(238, 242, 250);  \n"
"}")
        self.tableWidget_transactions.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_transactions.setObjectName("tableWidget_transactions")
        self.tableWidget_transactions.setColumnCount(6)
        self.tableWidget_transactions.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_transactions.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_transactions.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_transactions.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_transactions.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_transactions.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_transactions.setHorizontalHeaderItem(5, item)
        self.tableWidget_transactions.horizontalHeader().setDefaultSectionSize(95)
        self.label_viewinfo = QtWidgets.QLabel(self.page_wallet)
        self.label_viewinfo.setGeometry(QtCore.QRect(140, 400, 441, 16))
        self.label_viewinfo.setObjectName("label_viewinfo")
        self.frame_maketransaction = QtWidgets.QFrame(self.page_wallet)
        self.frame_maketransaction.setGeometry(QtCore.QRect(30, 300, 631, 251))
        self.frame_maketransaction.setStyleSheet("QFrame#frame_maketransaction{border:1px solid gray;\n"
"border-radius:20px;\n"
"background-color:rgb(255, 218, 144)\n"
"}")
        self.frame_maketransaction.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_maketransaction.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_maketransaction.setObjectName("frame_maketransaction")
        self.pushButton_cancel = QtWidgets.QPushButton(self.frame_maketransaction)
        self.pushButton_cancel.setGeometry(QtCore.QRect(500, 210, 93, 28))
        self.pushButton_cancel.setStyleSheet("background-color: rgb(197, 75, 53);")
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.lineEdit_From_account = QtWidgets.QLineEdit(self.frame_maketransaction)
        self.lineEdit_From_account.setGeometry(QtCore.QRect(30, 80, 141, 31))
        self.lineEdit_From_account.setStyleSheet("font:rgb(140, 148, 148)")
        self.lineEdit_From_account.setText("")
        self.lineEdit_From_account.setObjectName("lineEdit_From_account")
        self.label_3 = QtWidgets.QLabel(self.frame_maketransaction)
        self.label_3.setGeometry(QtCore.QRect(30, 50, 131, 16))
        self.label_3.setStyleSheet("background-color:rgb(255, 218, 144)")
        self.label_3.setObjectName("label_3")
        self.label_17 = QtWidgets.QLabel(self.frame_maketransaction)
        self.label_17.setGeometry(QtCore.QRect(30, 120, 171, 21))
        self.label_17.setStyleSheet("background-color:rgb(255, 218, 144)")
        self.label_17.setObjectName("label_17")
        self.frame_5 = QtWidgets.QFrame(self.frame_maketransaction)
        self.frame_5.setGeometry(QtCore.QRect(30, 150, 571, 52))
        self.frame_5.setStyleSheet("QFrame#frame_5{background-color:rgb(255, 218, 144)}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(20)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lineEdit_To_account = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_To_account.setText("")
        self.lineEdit_To_account.setObjectName("lineEdit_To_account")
        self.horizontalLayout_5.addWidget(self.lineEdit_To_account)
        self.lineEdit_To_customer = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_To_customer.setText("")
        self.lineEdit_To_customer.setObjectName("lineEdit_To_customer")
        self.horizontalLayout_5.addWidget(self.lineEdit_To_customer)
        self.lineEdit_amount = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_amount.setText("")
        self.lineEdit_amount.setObjectName("lineEdit_amount")
        self.horizontalLayout_5.addWidget(self.lineEdit_amount)
        self.comboBox_ttype = QtWidgets.QComboBox(self.frame_5)
        self.comboBox_ttype.setObjectName("comboBox_ttype")
        self.comboBox_ttype.addItem("")
        self.comboBox_ttype.addItem("")
        self.horizontalLayout_5.addWidget(self.comboBox_ttype)
        self.pushButton_make2 = QtWidgets.QPushButton(self.frame_maketransaction)
        self.pushButton_make2.setGeometry(QtCore.QRect(390, 210, 93, 28))
        self.pushButton_make2.setStyleSheet("background-color: rgb(98, 197, 146);")
        self.pushButton_make2.setObjectName("pushButton_make2")
        self.label_18 = QtWidgets.QLabel(self.frame_maketransaction)
        self.label_18.setGeometry(QtCore.QRect(260, 10, 161, 16))
        self.label_18.setStyleSheet("background-color:rgb(255, 218, 144)")
        self.label_18.setObjectName("label_18")
        self.pushButton_make = QtWidgets.QPushButton(self.page_wallet)
        self.pushButton_make.setGeometry(QtCore.QRect(470, 257, 211, 31))
        self.pushButton_make.setStyleSheet("QPushButton{border:0px solid;\n"
"border-radius:5px;\n"
"background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(198, 213, 234, 255), stop:1 rgba(238, 242, 250, 255))\n"
"}")
        self.pushButton_make.setObjectName("pushButton_make")
        self.label_35 = QtWidgets.QLabel(self.page_wallet)
        self.label_35.setGeometry(QtCore.QRect(30, 10, 221, 16))
        self.label_35.setObjectName("label_35")
        self.stackedWidget.addWidget(self.page_wallet)
        self.page_transfer = QtWidgets.QWidget()
        self.page_transfer.setObjectName("page_transfer")
        self.groupBox_4 = QtWidgets.QGroupBox(self.page_transfer)
        self.groupBox_4.setGeometry(QtCore.QRect(30, 20, 671, 541))
        self.groupBox_4.setObjectName("groupBox_4")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton.setGeometry(QtCore.QRect(420, 50, 121, 19))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_2.setGeometry(QtCore.QRect(250, 50, 115, 19))
        self.radioButton_2.setObjectName("radioButton_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setGeometry(QtCore.QRect(60, 50, 141, 16))
        self.label_5.setObjectName("label_5")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.groupBox_4)
        self.stackedWidget_2.setGeometry(QtCore.QRect(30, 80, 571, 171))
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_default = QtWidgets.QWidget()
        self.page_default.setObjectName("page_default")
        self.label_26 = QtWidgets.QLabel(self.page_default)
        self.label_26.setGeometry(QtCore.QRect(150, 80, 301, 20))
        self.label_26.setObjectName("label_26")
        self.stackedWidget_2.addWidget(self.page_default)
        self.page_time = QtWidgets.QWidget()
        self.page_time.setObjectName("page_time")
        self.frame_4 = QtWidgets.QFrame(self.page_time)
        self.frame_4.setGeometry(QtCore.QRect(10, 10, 551, 151))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        self.label_4.setGeometry(QtCore.QRect(20, 10, 311, 21))
        self.label_4.setObjectName("label_4")
        self.label_23 = QtWidgets.QLabel(self.frame_4)
        self.label_23.setGeometry(QtCore.QRect(20, 60, 72, 15))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.frame_4)
        self.label_24.setGeometry(QtCore.QRect(290, 60, 72, 15))
        self.label_24.setObjectName("label_24")
        self.lineEdit_fromt = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_fromt.setGeometry(QtCore.QRect(90, 60, 151, 21))
        self.lineEdit_fromt.setObjectName("lineEdit_fromt")
        self.lineEdit_tot = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_tot.setGeometry(QtCore.QRect(360, 60, 141, 21))
        self.lineEdit_tot.setObjectName("lineEdit_tot")
        self.pushButton_searchtime = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_searchtime.setGeometry(QtCore.QRect(410, 120, 141, 31))
        self.pushButton_searchtime.setStyleSheet("QPushButton{border:0px solid;\n"
"border-radius:5px;\n"
"background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(198, 213, 234, 255), stop:1 rgba(238, 242, 250, 255))\n"
"}")
        self.pushButton_searchtime.setIcon(icon3)
        self.pushButton_searchtime.setObjectName("pushButton_searchtime")
        self.stackedWidget_2.addWidget(self.page_time)
        self.page_type = QtWidgets.QWidget()
        self.page_type.setObjectName("page_type")
        self.comboBox_stype = QtWidgets.QComboBox(self.page_type)
        self.comboBox_stype.setGeometry(QtCore.QRect(180, 70, 151, 22))
        self.comboBox_stype.setObjectName("comboBox_stype")
        self.comboBox_stype.addItem("")
        self.comboBox_stype.addItem("")
        self.comboBox_stype.addItem("")
        self.comboBox_stype.addItem("")
        self.label_25 = QtWidgets.QLabel(self.page_type)
        self.label_25.setGeometry(QtCore.QRect(40, 20, 161, 21))
        self.label_25.setObjectName("label_25")
        self.lineEdit_param2 = QtWidgets.QLineEdit(self.page_type)
        self.lineEdit_param2.setGeometry(QtCore.QRect(390, 70, 113, 21))
        self.lineEdit_param2.setObjectName("lineEdit_param2")
        self.pushButton_searchtype = QtWidgets.QPushButton(self.page_type)
        self.pushButton_searchtype.setGeometry(QtCore.QRect(420, 130, 141, 31))
        self.pushButton_searchtype.setStyleSheet("QPushButton{border:0px solid;\n"
"border-radius:5px;\n"
"background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(198, 213, 234, 255), stop:1 rgba(238, 242, 250, 255))\n"
"}")
        self.pushButton_searchtype.setIcon(icon3)
        self.pushButton_searchtype.setObjectName("pushButton_searchtype")
        self.label_36 = QtWidgets.QLabel(self.page_type)
        self.label_36.setGeometry(QtCore.QRect(350, 70, 21, 21))
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.page_type)
        self.label_37.setGeometry(QtCore.QRect(40, 70, 101, 21))
        self.label_37.setObjectName("label_37")
        self.stackedWidget_2.addWidget(self.page_type)
        self.tableWidget_transactions_2 = QtWidgets.QTableWidget(self.groupBox_4)
        self.tableWidget_transactions_2.setGeometry(QtCore.QRect(10, 310, 611, 211))
        self.tableWidget_transactions_2.setStyleSheet("QHeaderView                   \n"
"{\n"
"    background:transparent;\n"
"    \n"
"\n"
"}\n"
"QHeaderView::section          \n"
"{                 \n"
"    background-color:rgb(238, 242, 250);          \n"
"    border:none;                \n"
"    text-align:center;             \n"
"    min-height:35px;               \n"
"    max-height:35px;               \n"
"    margin-left:0px;              \n"
"    padding-left:0px;\n"
"    border: 0px solid;      \n"
"}\n"
"QTableWidget{\n"
"\n"
"background:rgb(238, 242, 250); \n"
"border:1px solid #242424;\n"
"gridline-color:#242424;\n"
"selection-color:#242424;\n"
"selection-background-color:rgb(198, 213, 234);\n"
"\n"
"}\n"
"QTableCornerButton::section {\n"
"background-color:rgb(238, 242, 250);  \n"
"}")
        self.tableWidget_transactions_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_transactions_2.setObjectName("tableWidget_transactions_2")
        self.tableWidget_transactions_2.setColumnCount(6)
        self.tableWidget_transactions_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_transactions_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_transactions_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_transactions_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_transactions_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_transactions_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_transactions_2.setHorizontalHeaderItem(5, item)
        self.tableWidget_transactions_2.horizontalHeader().setDefaultSectionSize(97)
        self.label_27 = QtWidgets.QLabel(self.groupBox_4)
        self.label_27.setGeometry(QtCore.QRect(10, 270, 141, 20))
        self.label_27.setObjectName("label_27")
        self.stackedWidget.addWidget(self.page_transfer)
        self.horizontalLayout_2.addWidget(self.stackedWidget)
        self.horizontalLayout.addWidget(self.main_page)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        self.stackedWidget_2.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Good evening,"))
        self.label_surname.setText(_translate("MainWindow", "Ms. XX"))
        self.pushButton_profile.setText(_translate("MainWindow", " Profile            "))
        self.pushButton_home.setText(_translate("MainWindow", " Home             "))
        self.pushButton_wallet.setText(_translate("MainWindow", " Wallet            "))
        self.pushButton_transfer.setText(_translate("MainWindow", " Search            "))
        self.pushButton_logout.setText(_translate("MainWindow", "Logout         "))
        self.groupBox.setTitle(_translate("MainWindow", "Profile"))
        self.label_8.setText(_translate("MainWindow", "First Name"))
        self.label_14.setText(_translate("MainWindow", "Last Name"))
        self.label_9.setText(_translate("MainWindow", "Gender"))
        self.label_10.setText(_translate("MainWindow", "Birthday"))
        self.label_16.setText(_translate("MainWindow", "Phone Number"))
        self.label_15.setText(_translate("MainWindow", "Email"))
        self.pushButton_changepwd.setText(_translate("MainWindow", "Change Password"))
        self.pushButton_edit_profile.setText(_translate("MainWindow", "Edit Profile"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Security Information"))
        self.label_11.setText(_translate("MainWindow", "Customer ID"))
        self.label_12.setText(_translate("MainWindow", "Certification Type"))
        self.label_13.setText(_translate("MainWindow", "Certification ID"))
        self.label_19.setText(_translate("MainWindow", "Chaneg Password"))
        self.label_20.setText(_translate("MainWindow", "Old Password"))
        self.label_21.setText(_translate("MainWindow", "New Password"))
        self.label_22.setText(_translate("MainWindow", "Confirm password"))
        self.pushButton_confirmpwd.setText(_translate("MainWindow", "Confirm"))
        self.pushButton_cancelpwd.setText(_translate("MainWindow", "Cancel"))
        self.label_7.setText(_translate("MainWindow", "Login Hitory"))
        item = self.tableWidget_login.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Date"))
        item = self.tableWidget_login.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Time"))
        self.label_6.setText(_translate("MainWindow", "Frequent Contact"))
        item = self.tableWidget_recentContect.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget_recentContect.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Customer ID"))
        item = self.tableWidget_recentContect.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Account ID"))
        self.pushButton_qt.setText(_translate("MainWindow", "Quick transfer"))
        self.label_28.setText(_translate("MainWindow", "Balance"))
        self.label_image.setText(_translate("MainWindow", " "))
        self.label_29.setText(_translate("MainWindow", "Login Time"))
        self.label_logintime.setText(_translate("MainWindow", "3"))
        self.label_30.setText(_translate("MainWindow", "Customer ID"))
        self.label_loginid.setText(_translate("MainWindow", "2"))
        self.label_31.setText(_translate("MainWindow", "Name"))
        self.label_loginname.setText(_translate("MainWindow", "1"))
        self.pushButton_cancel_4.setText(_translate("MainWindow", "Cancel"))
        self.lineEdit_From_account_4.setPlaceholderText(_translate("MainWindow", "From_account"))
        self.label_41.setText(_translate("MainWindow", "From account:"))
        self.label_42.setText(_translate("MainWindow", "Detail Information:"))
        self.lineEdit_To_account_4.setPlaceholderText(_translate("MainWindow", "To_account"))
        self.lineEdit_To_customer_4.setPlaceholderText(_translate("MainWindow", "To_customer"))
        self.lineEdit_amount_4.setPlaceholderText(_translate("MainWindow", "amount"))
        self.comboBox_ttype_4.setItemText(0, _translate("MainWindow", "HKD"))
        self.comboBox_ttype_4.setItemText(1, _translate("MainWindow", "Pound"))
        self.pushButton_make2_4.setText(_translate("MainWindow", "Confirm"))
        self.label_43.setText(_translate("MainWindow", "Make transaction"))
        item = self.tableWidget_accounts.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Account ID"))
        item = self.tableWidget_accounts.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Account Type"))
        item = self.tableWidget_accounts.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Currency Type"))
        item = self.tableWidget_accounts.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Create Time"))
        item = self.tableWidget_accounts.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Balance"))
        self.label_2.setText(_translate("MainWindow", "Transaction History"))
        item = self.tableWidget_transactions.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget_transactions.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "In Account"))
        item = self.tableWidget_transactions.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Out Account"))
        item = self.tableWidget_transactions.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Amount"))
        item = self.tableWidget_transactions.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Currency "))
        item = self.tableWidget_transactions.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Date"))
        self.label_viewinfo.setText(_translate("MainWindow", "Select an account to view and make transactions!"))
        self.pushButton_cancel.setText(_translate("MainWindow", "Cancel"))
        self.lineEdit_From_account.setPlaceholderText(_translate("MainWindow", "From_account"))
        self.label_3.setText(_translate("MainWindow", "From account:"))
        self.label_17.setText(_translate("MainWindow", "Detail Information:"))
        self.lineEdit_To_account.setPlaceholderText(_translate("MainWindow", "To_account"))
        self.lineEdit_To_customer.setPlaceholderText(_translate("MainWindow", "To_customer"))
        self.lineEdit_amount.setPlaceholderText(_translate("MainWindow", "amount"))
        self.comboBox_ttype.setItemText(0, _translate("MainWindow", "HKD"))
        self.comboBox_ttype.setItemText(1, _translate("MainWindow", "Pound"))
        self.pushButton_make2.setText(_translate("MainWindow", "Confirm"))
        self.label_18.setText(_translate("MainWindow", "Make transaction"))
        self.pushButton_make.setText(_translate("MainWindow", "Make Transaction"))
        self.label_35.setText(_translate("MainWindow", "Account List"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Search Transactions"))
        self.radioButton.setText(_translate("MainWindow", "Other Types"))
        self.radioButton_2.setText(_translate("MainWindow", "Time Period"))
        self.label_5.setText(_translate("MainWindow", "Seasrch base on:"))
        self.label_26.setText(_translate("MainWindow", "please select a type to search!"))
        self.label_4.setText(_translate("MainWindow", "e.g. from 1995-03-05 to 1995-03-30"))
        self.label_23.setText(_translate("MainWindow", "from"))
        self.label_24.setText(_translate("MainWindow", "to"))
        self.pushButton_searchtime.setText(_translate("MainWindow", "Search"))
        self.comboBox_stype.setItemText(0, _translate("MainWindow", "transaction_id"))
        self.comboBox_stype.setItemText(1, _translate("MainWindow", "amount"))
        self.comboBox_stype.setItemText(2, _translate("MainWindow", "timepoint_date"))
        self.comboBox_stype.setItemText(3, _translate("MainWindow", "account_id"))
        self.label_25.setText(_translate("MainWindow", "Type-based Search"))
        self.pushButton_searchtype.setText(_translate("MainWindow", "Search"))
        self.label_36.setText(_translate("MainWindow", "="))
        self.label_37.setText(_translate("MainWindow", "Condition:"))
        item = self.tableWidget_transactions_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget_transactions_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "In Account"))
        item = self.tableWidget_transactions_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Out Account"))
        item = self.tableWidget_transactions_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Amount"))
        item = self.tableWidget_transactions_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Currency"))
        item = self.tableWidget_transactions_2.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Date"))
        self.label_27.setText(_translate("MainWindow", "Search Result"))
